version: '3.9'

services:
  mysql_container:
    image: mysql:5.6
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=Strong_Password123!
      - MYSQL_DATABASE=mydatabase
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"

volumes:
  db_data:
