version: '3'
services:
  app:
    build: .
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: Strong_Password123!
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      SECRET_KEY: SuperSecr3t123
    volumes:
      - ./app:/app
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "5000:5000"

  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    labels:
      project: "flask"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Strong_Password123!
      MYSQL_DATABASE: mydatabase

volumes:
  mysql-data:
    driver: local
